# Generated by Django 5.0.3 on 2024-04-16 08:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accommodations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodation',
            name='is_favorite',
            field=models.ManyToManyField(blank=True, related_name='favorite_accommodations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accommodationimage',
            name='accommodation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='accommodations.accommodation'),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='accommodation_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accommodations.accommodationtype'),
        ),
        migrations.AddField(
            model_name='staydate',
            name='accommodation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stay_dates', to='accommodations.accommodation'),
        ),
    ]
